springdoc:
  swagger-ui:
    path: docs.html
  version: v1
  paths-to-match:
    - /flight/**
    - /auth/**
    - /traveler/**
    - /order/**
spring:
  mvc:
    converters:
      preferred-json-mapper: 'gson'